module.exports.GenericTrait = require('./Trait.GenericTrait')
module.exports.CanvasFingerprint = require('./Trait.CanvasFingerprint')
module.exports.SystemFonts = require('./Trait.SystemFonts')
module.exports.TimeZone = require('./Trait.TimeZone')
module.exports.Nothing = require('./Trait.Nothing')
