module.exports.UserAgent = require('@pouk/idem-client-probe-user-agent')
module.exports.TimezoneOffset = require('@pouk/idem-client-probe-timezone-offset')
module.exports.SystemFonts = require('@pouk/idem-client-probe-system-fonts')
module.exports.NavigatorPlugins = require('@pouk/idem-client-probe-navigator-plugins')
module.exports.MimeTypes = require('@pouk/idem-client-probe-mime-types')
